name: Setup Python on Windows Server 2022

on:
  push:
    branches:
      - main

jobs:
  test-python:
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11.7']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Display system details
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
       

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
        env:
         GOBUILD_LOCALCACHE_DIR: C:\actions-runner\_work\cart-main-gf-nov-14\cart-main-gf-nov-14\..\gobuild-cache

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt