name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04
      env:
        PIP_ROOT_USER_ACTION: ignore
    
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release

      - name: fix pip issue
        run: mkdir -p /github/home/.cache/pip
      - name: Get container ID
        id: get_container_id
        run: |
          container_id=$(docker ps -q -f ancestor=ubuntu:20.04)
          full_container_id=$(docker inspect --format="{{.Id}}" $container_id)
          echo "Container ID: $full_container_id"
          echo "container_id=$full_container_id" >> $GITHUB_ENV
          
      - name: Set PIP_ROOT_USER_ACTION in Docker
        run: |
          /usr/bin/docker exec -e PIP_ROOT_USER_ACTION=ignore ${container_id} sh -c "echo 'PIP_ROOT_USER_ACTION: ' \$PIP_ROOT_USER_ACTION"
      
      - name: Show Container ID and Environment Variable
        run: |
          echo "Container ID used: ${container_id}"
          /usr/bin/docker exec ${container_id} sh -c "echo 'PIP_ROOT_USER_ACTION: ' \$PIP_ROOT_USER_ACTION"
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
        # env:
        #   PIP_ROOT_USER_ACTION: ignore

      
      - name: Verify PIP_ROOT_USER_ACTION in Docker
        run: |
          /usr/bin/docker exec ${container_id} sh -c "echo 'PIP_ROOT_USER_ACTION: ' \$PIP_ROOT_USER_ACTION"
          
      - name: Show Container ID and Release Info
        run: |
          echo "Container ID used: ${container_id}"
          /usr/bin/docker exec ${container_id} sh -c "cat /etc/*release | grep ^ID"
          

  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'