name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-small-3.9.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            apt-get update && apt-get install -y sudo
          fi
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release
      - name: Change ownership of /github/home
        run: sudo chown -R $(whoami) /github/home
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt