name: PIP_ROOT_USER_ACTION ignored 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:

      - name: 	Clear cache
        run: |
            mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
            mkdir -p "${{ runner.tool_cache }}"
      - uses: actions/checkout@v4
     
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"
      - name: Print environment variables
        run: env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
         