name: PIP_ROOT_USER_ACTION ignored 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    # container: ubuntu:20.04
    container:
      image: ubuntu:20.04
      # options: --env PIP_ROOT_USER_ACTION=ignore  # Add the environment variable here

    steps:

      - uses: actions/checkout@v4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release
      - name: Check Docker Container
        run: |
          echo "Running inside Docker container:"
          cat /etc/os-release
          docker --version
    
      - name: fix pip issue
        run: mkdir -p /github/home/.cache/pip
      - name: Set up pip configuration
        run: |
          mkdir -p ~/.pip
          echo "[global]" > ~/.pip/pip.conf
          echo "root-user-action = ignore" >> ~/.pip/pip.conf
          echo "disable-pip-version-check = true" >> ~/.pip/pip.conf
          echo "no-warn-script-location = true" >> ~/.pip/pip.conf

          
     
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.14"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      
      - name: Echo PIP_ROOT_USER_ACTION
        run: echo "Value of PIP_ROOT_USER_ACTION is $PIP_ROOT_USER_ACTION"
 
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv1-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt