name: Test PR Changes related to AGENT_TOOLSDIRECTORY on macOS
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        python-version: ['3.8.15']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install OpenSSL
        run: |
          brew install openssl
          brew link --force openssl
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade certifi
          pip install -r requirements.txt