name: Docker Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          buildx-version: latest

      - name: Run Docker Compose
        run: |
          docker-compose run --rm -e PIP_ROOT_USER_ACTION=ignore myservice
      - name: Setup Python
        uses: priya-kinthali/setup-python@test-930
        with:
          python-version: "3.10.14"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
         
