name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      # - name: Install lsb-release
      #   run: |
      #     apt-get update
      #     apt-get install -y lsb-release
      # - name: Create /etc/lsb-release
      #   run: |
      #     echo "DISTRIB_RELEASE=22.04" | tee -a /etc/lsb-release
      - name: fix pip issue
        run: mkdir -p /github/home/.cache/pip

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'