name: Test Setup Python 3.10 #issue-1116-after manual installation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-python310:
    runs-on: [self-hosted]
    # env:
    #   AGENT_TOOLSDIRECTORY: "C:\\hostedtoolcache\\windows"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13.4
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.4'

      - name: Verify Python version
        run: python --version