name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
      env:
        PIP_ROOT_USER_ACTION: ignore
    strategy:
      matrix:
        python: [3.11.6]
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            apt-get update && apt-get install -y sudo
          fi
      - name: Run and inspect Docker container
        run: |
          docker inspect --format '{{ .Config.Env }}' ${{ steps.get_container_id.outputs.container_id }}
      - name: Check environment variable in running container
        run: |
          docker ps
          docker exec ${{ steps.get_container_id.outputs.container_id }} /bin/bash -c 'echo $PIP_ROOT_USER_ACTION'
      - name: Check ownership
        run: ls -ld /github/home
      - name: Change ownership of /github/home
        run: sudo chown -R $(whoami) /github/home

      - name: Check ownership
        run: ls -ld /github/home
      - name: Run and inspect Docker container
        run: |
          docker inspect --format '{{ .Config.Env }}' ${{ steps.get_container_id.outputs.container_id }}
      - name: Upgrade pip in Docker container
        run: |
           docker exec ${{ steps.get_container_id.outputs.container_id }} /bin/bash -c "apt-get update && apt-get install -y python3 python3-pip && PIP_ROOT_USER_ACTION=ignore python3 -m pip install --upgrade pip"
