name: test
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-24.04, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Get Python version
        run: python --version
      - name: Install pipx
        run: python -m pip install --user pipx
      - name: Ensure pipx uses the correct Python
        run: python -m pipx ensurepath
      - name: Get pipx version
        run: pipx --version
      - name: Install Python Package
        run: pipx install .
