name: Test PR Changes related to AGENT_TOOLSDIRECTORY on macOS
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted]
        python-version: ['3.10.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Set up environment variables for OpenSSL
      #   run: |
      #     echo "LDFLAGS=-L/usr/local/opt/openssl/lib" >> $GITHUB_ENV
      #     echo "CPPFLAGS=-I/usr/local/opt/openssl/include" >> $GITHUB_ENV
      #     echo "PATH=/usr/local/opt/openssl/bin:$PATH" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  
      - name: Verify SSL support
        run: python3 -m ssl
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
