name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            apt-get update && apt-get install -y sudo
          fi
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release
      - name: Change ownership of /github/home
        run: sudo chown -R $(whoami) /github/home
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Get System Information
        id: system-info
        run: |
          echo "ARCH=$(uname -m)" >> $GITHUB_ENV
          echo "OS_VERSION=$(lsb_release -rs)" >> $GITHUB_ENV
          echo "OS_NAME=$(lsb_release -is)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: -${{ runner.os }}-${{ env.ARCH }}-${{ env.OS_VERSION }}-${{ env.OS_NAME }}-python-${{ python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            -${{ runner.os }}-${{ env.ARCH }}-${{ env.OS_VERSION }}-${{ env.OS_NAME }}-python-${{ python-version }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt