name: Test PR Changes related to AGENT_TOOLSDIRECTORY on macOS
on: 
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, self-hosted]
        python-version: ['3.8.10', '3.9.13', '3.10.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        # uses: actions/setup-python@v5
        uses: priya-kinthali/setup-python@test-708-new
        with:
          python-version: ${{ matrix.python-version }}
        # env:
        #   PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"
          # cache: 'pip'  
      # - name: Verify SSL support
      #   run: python3 -m ssl
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
