name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        PIP_ROOT_USER_ACTION: ignore
    
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release

      - name: fix pip issue
        run: mkdir -p /github/home/.cache/pip
      - name: Access release information
        run: |
          cat /etc/*release | grep ^ID
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'