name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        PIP_ROOT_USER_ACTION: ignore
    
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release

      - name: fix pip issue
        run: mkdir -p /github/home/.cache/pip
      - name: Get container ID
        id: get_container_id
        run: |
          container_id=$(docker ps -q -f ancestor=ubuntu:22.04)
          echo "Container ID: $container_id"
          echo "container_id=$container_id" >> $GITHUB_ENV
          
      - name: Set PIP_ROOT_USER_ACTION in Docker
        run: |
          /usr/bin/docker exec -e PIP_ROOT_USER_ACTION=ignore ${{ env.container_id }} sh -c "echo 'export PIP_ROOT_USER_ACTION=ignore' >> /etc/profile"
      - name: Verify PIP_ROOT_USER_ACTION in Docker
        run: |
          /usr/bin/docker exec ${{ env.container_id }} sh -c "echo 'PIP_ROOT_USER_ACTION: ' \$PIP_ROOT_USER_ACTION"
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12.6]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'