name: Test PR Changes related to AGENT_TOOLSDIRECTORY on macOS
on: 
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-latest, macos-13, self-hosted]
        python-version: ['3.11.9']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: priya-kinthali/setup-python@test-708
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  
        env:
          AGENT_TOOLSDIRECTORY: /Users/lakshmipriya/hostedtoolcache
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
